// Optional development-only check. The deployed site never loads Playwright.
import { createRequire } from 'node:module';
import { readFile, writeFile, mkdir, mkdtemp } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { resolve, join } from 'node:path';
import assert from 'node:assert/strict';

const require = createRequire(import.meta.url);
const { chromium } = require(process.env.SMART_ESCAPE_PLAYWRIGHT || 'playwright');
const url = process.env.SMART_ESCAPE_URL || 'http://127.0.0.1:5173';
const browser = await chromium.launch({ channel: 'chrome', headless: true });
const page = await browser.newPage({ viewport: { width: 1440, height: 1050 }, reducedMotion: 'reduce' });
const errors = [], checks = [];
page.on('pageerror', error => errors.push(error.message));
const passed = label => { checks.push(label); console.log(`PASS ${label}`); };
const current = () => page.locator('.route-result');
const status = () => page.locator('.status-pill').innerText();
const select = id => page.locator('#start-select').selectOption(id);
const toggle = key => page.locator(`[data-focus="${key}"]`).click();
const reset = () => toggle('reset');
const temp = await mkdtemp(join(tmpdir(), 'smart-escape-check-'));
await mkdir('screenshots', { recursive: true });
async function upload(content, name = 'building.json') {
  const path = join(temp, name); await writeFile(path, content, 'utf8');
  const pending = page.waitForEvent('filechooser');
  await page.getByRole('button', { name: /^(Import building|ভবন আমদানি)$/ }).first().click();
  const chooser = await pending; await chooser.setFiles(path);
}
try {
  await page.goto(url);
  await page.getByRole('button', { name: 'Load sample', exact: true }).click();
  await page.locator('#start-select').waitFor(); await select('R1');
  assert.equal(await page.locator('.route-cost strong').innerText(), '7');
  assert.deepEqual(await page.locator('.route-sequence .sequence-id').allTextContents(), ['R1', 'C1', 'C2', 'E1']);
  assert.equal(await page.locator('.location').count(), 8); assert.equal(await page.locator('.corridor').count(), 9);
  passed('sample import and R1 baseline cost 7');
  await page.screenshot({ path: resolve('screenshots/baseline.png'), fullPage: true });
  await toggle('blocked_nodes-C2');
  assert.equal(await page.locator('.route-cost strong').innerText(), '11');
  assert.deepEqual(await page.locator('.route-sequence .sequence-id').allTextContents(), ['R1', 'C1', 'C3', 'C4', 'E2']);
  assert.equal(await page.locator('.corridor.on-route').count(), 4);
  passed('C2 reroute cost 11 and matching highlighted corridors');
  await page.screenshot({ path: resolve('screenshots/reroute-c2.png'), fullPage: true });
  await reset(); await toggle('closed_exits-E1'); await toggle('closed_exits-E2');
  assert.equal(await status(), 'No route available'); assert.equal(await page.locator('.corridor.on-route').count(), 0);
  passed('both exits closed removes stale route');
  await reset(); await select('R2'); assert.equal(await page.locator('.route-cost strong').innerText(), '7');
  passed('R2 baseline cost 7');
  await select('R1'); await toggle('blocked_nodes-R1'); assert.equal(await status(), 'Starting location blocked');
  assert.equal(await page.locator('#start-select').inputValue(), 'R1');
  passed('blocked selected start remains selected with distinct message');
  await reset(); assert.equal(await page.locator('.route-cost strong').innerText(), '7');
  await toggle('blocked_nodes-C2');
  const previous = await current().innerText();
  await upload('{broken', 'malformed.json'); await page.locator('.error-banner').waitFor();
  assert.equal(await current().innerText(), previous); assert.match(await page.locator('.error-banner').innerText(), /not valid JSON/);
  passed('malformed JSON preserves building, start, hazards and route');
  await upload('{"building":"invalid","nodes":[]}', 'invalid.json');
  await page.waitForFunction(() => document.querySelector('.error-banner')?.textContent.includes('between 2 and 60'));
  assert.equal(await current().innerText(), previous); passed('invalid schema preserves previous simulation');
  const fixture = JSON.parse(await readFile('data/building.json', 'utf8'));
  fixture.building = 'Initial hazards browser check'; fixture.initial_state = { blocked_nodes: ['R1', 'C2'], blocked_edges: ['L04'], closed_exits: ['E1'] };
  await upload(JSON.stringify(fixture), 'initial-hazards.json');
  await page.waitForFunction(() => document.querySelector('.building-bar h2')?.textContent === 'Initial hazards browser check');
  await toggle('blocked_nodes-R1'); await toggle('blocked_nodes-C2'); await toggle('blocked_edges-L04'); await toggle('closed_exits-E1'); await select('R1');
  assert.equal(await page.locator('.route-cost strong').innerText(), '7');
  await reset(); assert.equal(await status(), 'Starting location blocked');
  for (const key of ['blocked_nodes-R1', 'blocked_nodes-C2', 'blocked_edges-L04', 'closed_exits-E1']) assert.equal(await page.locator(`[data-focus="${key}"]`).getAttribute('aria-pressed'), 'true');
  assert.equal(await page.locator('[data-focus="closed_exits-E2"]').getAttribute('aria-pressed'), 'false');
  passed('reset restores all non-empty original hazard arrays and retains blocked start');
  await toggle('language'); assert.equal(await page.locator('html').getAttribute('lang'), 'bn');
  assert.equal(await status(), 'শুরুর স্থান অবরুদ্ধ');
  await toggle('closed_exits-E2'); await toggle('blocked_nodes-R1'); assert.equal(await status(), 'কোনো পথ পাওয়া যায়নি');
  await upload('{broken', 'malformed.json'); await page.locator('.error-banner').waitFor();
  assert.match(await page.locator('.error-banner').innerText(), /বৈধ JSON নয়/); passed('Bangla blocked-start, no-route and import error messages');
  assert.equal(await page.locator('.footer-name').innerText(), 'স্মার্ট এস্কেপ / অনুশীলন');
  passed('practice footer is localized in Bangla');
  await page.locator('[data-focus="dismiss-error"]').focus(); await page.keyboard.press('Enter');
  assert.equal(await page.locator('.error-banner').count(), 0);
  assert.equal(await page.evaluate(() => document.activeElement?.dataset?.focus), 'import-header');
  passed('dismissed error restores focus to a persistent import control');
  await page.setViewportSize({ width: 390, height: 844 });
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false);
  passed('390px Bangla layout has no horizontal page overflow');
  await page.screenshot({ path: resolve('screenshots/bangla-mobile.png'), fullPage: true });
  await page.setViewportSize({ width: 1440, height: 1050 }); await toggle('language');
  const untrusted = JSON.parse(await readFile('data/building.json', 'utf8'));
  untrusted.building = '<img src=x onerror="window.__unsafe=true">';
  untrusted.nodes[0].label = '<script>window.__unsafe=true</script>';
  await upload(JSON.stringify(untrusted), 'untrusted-labels.json');
  await page.waitForFunction(() => document.querySelector('.building-bar h2')?.textContent.startsWith('<img'));
  assert.equal(await page.locator('.building-bar img').count(), 0); assert.equal(await page.evaluate(() => window.__unsafe === true), false);
  await select('R1'); assert.equal(await page.locator('.route-cost strong').innerText(), '7'); passed('untrusted labels rendered as text, not HTML');
  await page.locator('[data-focus="blocked_nodes-C2"]').focus(); await page.keyboard.press('Enter');
  assert.equal(await page.locator('.route-cost strong').innerText(), '11');
  await page.keyboard.press('Enter'); assert.equal(await page.locator('.route-cost strong').innerText(), '7');
  passed('repeated keyboard condition toggles preserve focus');
  await upload(await readFile('data/building.json', 'utf8'), 'same-file.json');
  await page.waitForFunction(() => document.querySelector('.building-bar h2')?.textContent === 'East Annex - Practice Building'); await select('R1');
  await toggle('blocked_nodes-C2');
  await upload(await readFile('data/building.json', 'utf8'), 'same-file.json');
  await page.waitForFunction(() => document.querySelector('#start-select')?.value === '');
  assert.equal(await page.locator('[data-focus="blocked_nodes-C2"]').getAttribute('aria-pressed'), 'false');
  passed('same local file can be imported repeatedly');
  await select('R1');
  assert.equal(await page.locator('.corridor.on-route .corridor-line').first().evaluate(el => getComputedStyle(el).animationName), 'none');
  passed('reduced motion disables route animation');
  assert.deepEqual(errors, []); passed('no uncaught browser exceptions');
  await writeFile('screenshots/browser-results.json', JSON.stringify({ url, checks, count: checks.length, errors }, null, 2));
  console.log(`Browser checks passed: ${checks.length}`);
} finally { await browser.close(); }
