// Development-only browser acceptance for explicit local saved progress.
import { createRequire } from 'node:module';
import { readFile, writeFile, mkdtemp } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import assert from 'node:assert/strict';
const require = createRequire(import.meta.url);
const { chromium } = require(process.env.SMART_ESCAPE_PLAYWRIGHT || 'playwright');
const url = process.env.SMART_ESCAPE_URL || 'http://127.0.0.1:5173';
const browser = await chromium.launch({ channel: 'chrome', headless: true });
const page = await browser.newPage({ viewport: { width: 390, height: 844 } });
const errors = [], checks = []; page.on('pageerror', e => errors.push(e.message));
const pass = name => { checks.push(name); console.log(`PASS ${name}`); };
const click = token => page.locator(`[data-focus="${token}"]`).click();
const key = 'puku1:smart-escape:session:v1';
try {
  await page.goto(url); await click('restore-session');
  assert.match(await page.locator('main').innerText(), /no saved progress/); pass('absent saved progress gives a clear message');
  const fixture = JSON.parse(await readFile('data/building.json', 'utf8'));
  fixture.initial_state = { blocked_nodes: ['C2'], blocked_edges: ['L04'], closed_exits: ['E1'] };
  fixture.building = 'Saved progress reset fixture';
  const folder = await mkdtemp(join(tmpdir(), 'smart-escape-session-')); const file = join(folder, 'session.json');
  await writeFile(file, JSON.stringify(fixture));
  const chooser = page.waitForEvent('filechooser'); await click('import-header'); await (await chooser).setFiles(file);
  await page.locator('#start-select').waitFor();
  for (const id of ['blocked_nodes-C2', 'blocked_edges-L04', 'closed_exits-E1']) await click(id);
  await page.locator('#start-select').selectOption('R1');
  await click('blocked_nodes-R1'); await click('blocked_edges-L08'); await click('closed_exits-E2');
  await click('language'); await click('hazard'); await click('save-session');
  const saved = JSON.parse(await page.evaluate(k => localStorage.getItem(k), key));
  assert.deepEqual(saved.state, { blocked_nodes: ['R1'], blocked_edges: ['L08'], closed_exits: ['E2'] });
  assert.equal(saved.startId, 'R1'); assert.equal(saved.language, 'bn'); assert.equal(saved.mode, 'hazard');
  pass('save captures all hazard categories, blocked start, Bangla and mode');
  await page.reload(); await click('restore-session');
  await page.locator('#start-select').waitFor(); assert.equal(await page.locator('#start-select').inputValue(), 'R1');
  assert.equal(await page.locator('.status-pill').innerText(), 'শুরুর স্থান অবরুদ্ধ');
  assert.equal(await page.locator('[data-focus="hazard"]').getAttribute('aria-pressed'), 'true');
  for (const id of ['blocked_nodes-R1', 'blocked_edges-L08', 'closed_exits-E2']) assert.equal(await page.locator(`[data-focus="${id}"]`).getAttribute('aria-pressed'), 'true');
  pass('reload and restore recover the validated session without losing blocked start');
  await click('reset');
  for (const id of ['blocked_nodes-C2', 'blocked_edges-L04', 'closed_exits-E1']) assert.equal(await page.locator(`[data-focus="${id}"]`).getAttribute('aria-pressed'), 'true');
  assert.equal(await page.locator('[data-focus="blocked_nodes-R1"]').getAttribute('aria-pressed'), 'false');
  assert.equal(await page.locator('.route-cost strong').innerText(), '11'); pass('reset after restore preserves all original imported hazard arrays');
  const before = await page.locator('.route-result').innerText();
  await page.evaluate(k => localStorage.setItem(k, '{broken'), key); await click('restore-session');
  assert.equal(await page.locator('.route-result').innerText(), before); assert.match(await page.locator('.error-banner').innerText(), /সংরক্ষিত অগ্রগতি/);
  pass('corrupt saved progress produces Bangla error and preserves current simulation');
  await page.evaluate(({ key, saved }) => { saved.state.blocked_nodes = ['missing']; localStorage.setItem(key, JSON.stringify(saved)); }, { key, saved });
  await click('restore-session'); assert.equal(await page.locator('.route-result').innerText(), before); assert.equal(await page.locator('.error-banner').count(), 1);
  pass('invalid saved hazard IDs are rejected before any current state changes');
  await click('clear-session'); assert.equal(await page.evaluate(k => localStorage.getItem(k), key), null);
  assert.equal(await page.locator('.route-result').innerText(), before); pass('clear removes only the stored snapshot and retains current simulation');
  await page.evaluate(() => Object.defineProperty(window, 'localStorage', { configurable: true, get() { throw new Error('blocked'); } }));
  await click('save-session'); assert.equal(await page.locator('.route-result').innerText(), before); assert.equal(await page.locator('.error-banner').count(), 1);
  pass('unavailable storage fails safely without changing current simulation');
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false);
  assert.deepEqual(errors, []); pass('Bangla saved progress controls fit mobile and introduce no browser exceptions');
  await writeFile('screenshots/session-results.json', JSON.stringify({ url, checks, count: checks.length, errors }, null, 2));
  console.log(`Saved progress checks passed: ${checks.length}`);
} finally { await browser.close(); }
